-- Script para insertar un usuario (Jefe) por cada oficina de bcoordinacion
-- Fecha: 2026-07-04 16:01:54
-- Total: 143 usuarios

USE tickets_system;

INSERT INTO Users (Fk_Role, Email, Password, Username, Full_Name, is_system_user) VALUES
(3, 'DESPACHO_DEL_ALCALDE@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'despacho_del_alcalde', 'LCDA. NORIS FIGUEROA', TRUE),
(3, 'ATENCION_AL_CIUDADANO@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'atencion_al_ciudadano', 'LCDA. KARLA JUAREZ GARCIA', TRUE),
(3, 'COORDINACION_DE_ATENCION_DE_SUGERENCIAS_Y_DENUNCIAS@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_atencion_de_sugerencias_y_denuncias', 'Coordinacion de Atencion de Sugerencias y Denuncias', TRUE),
(3, 'COORDINACION_DE_DIFUSION_DE_LA_INFORMACION@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_difusion_de_la_informacion', 'Coordinacion de Difusion de la informacion', TRUE),
(3, 'DIRECCION_EJECUTIVA_DEL_DESPACHO@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'direccion_ejecutiva_del_despacho', 'ABG. MARIO HERNAN IZARRA A.', TRUE),
(3, 'DIVISION_DE_CONTRATACIONES@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_contrataciones', 'LCDA. CARMEN DOS RAMOS', TRUE),
(3, 'CONSEJO_LOCAL_DE_PLANIFICACION_PUBLICA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'consejo_local_de_planificacion_publica', 'ING. JOSE GREGORIO HERNANDEZ ', TRUE),
(3, 'SINDICATURA_MUNICIPAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'sindicatura_municipal', 'ABG. ANNY GUIRIGAY', TRUE),
(3, 'DIVISION_DE_INMUEBLES@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_inmuebles', 'DIVISION DE INMUEBLES', TRUE),
(3, 'DIVISION_DE_ASUNTOS_ADMINISTRATIVOS@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_asuntos_administrativos', 'DIVISION DE ASUNTOS ADMINISTRATIVOS', TRUE),
(3, 'DIVISION_DE_ASUNTOS_LITIGIOSOS@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_asuntos_litigiosos', 'DIVISION DE ASUNTOS LITIGIOSOS', TRUE),
(3, 'AUDITORIA_INTERNA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'auditoria_interna', 'ABOG. NELSON VIVAS JAIMES', TRUE),
(3, 'COORDINACION_DE_DETERMINACION_DE_RESPONSABILIDADES@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_determinacion_de_responsabilidades', 'Coordinacion de Determinacion de Responsabilidades', TRUE),
(3, 'COORDINACION_DE_POTESTAD_INVESTIGATIVA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_potestad_investigativa', 'Coordinación de Potestad Investigativa', TRUE),
(3, 'COORDINACION_DE_CONTROL_POSTERIOR@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_control_posterior', 'LCDA. EDELIA RAQUEL GUERRERO ARAQUE', TRUE),
(3, 'REGISTRO_CIVIL_MUNICIPAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'registro_civil_municipal', 'REGISTRO CIVIL MUNICIPAL', TRUE),
(3, 'SECRETARIA_DE_GOBIERNO@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'secretaria_de_gobierno', 'SECRETARIA DE GOBIERNO', TRUE),
(3, 'DIRECCION_GENERAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'direccion_general', 'MSC JUAN MARTINEZ', TRUE),
(3, 'COORDINACION_DE_SEGURIDAD_Y_SALUD_LABORAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_seguridad_y_salud_laboral', 'DRA. INDIRA USECHE', TRUE),
(3, 'ARCHIVO_HISTORICO_DE_SAN_CRISTOBAL_DR_JOSE_JOAQUIN_VILLAMIZAR_MOLINA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'archivo_historico_de_san_cristobal_dr_jose_joaquin_villamizar_molina', 'FABIOLA MORENO', TRUE),
(3, 'COOPERACION_PROTOCOLAR_Y_RELACIONES_INTERINSTITUCIONALES@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'cooperacion_protocolar_y_relaciones_interinstitucionales', 'LCDO. FERNANDO ARRUNDOLL', TRUE),
(3, 'COORDINACION_DE_PROTOCOLO_Y_COOPERACION@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_protocolo_y_cooperacion', 'Coordinacion de Protocolo y Cooperacion', TRUE),
(3, 'TESORERIA_MUNICIPAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'tesoreria_municipal', 'LCDA. ANA MONCADA', TRUE),
(3, 'COORDINACION_DE_TRIBUTOS@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_tributos', 'Coordinacion de Tributos', TRUE),
(3, 'COORDINACION_DE_TAQUILLA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_taquilla', 'LCDA NERSA MONCADA', TRUE),
(3, 'INFORMATICA_Y_TECNOLOGIA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'informatica_y_tecnologia', 'ING. FERNANDO RUIZ ', TRUE),
(3, 'COORDINACION_DE_REDES@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_redes', 'ING. JOVAN FLOREZ ', TRUE),
(3, 'CORDINACION_DE_PROGRAMACION_Y_SISTEMAS@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'cordinacion_de_programacion_y_sistemas', 'ING. JORFREN CONTRERAS', TRUE),
(3, 'COORDINACION_DE_MANTENIMIENTO_DE_EQUIPOS_DE_COMPUTACION@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_mantenimiento_de_equipos_de_computacion', 'ING. ANGELA GARCIA', TRUE),
(3, 'CONSULTORIA_JURIDICA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'consultoria_juridica', 'ABOG. ESP. JESUS AGUILAR M.', TRUE),
(3, 'DIVISION_DE_JUSTICIA_MUNICIPAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_justicia_municipal', 'ABG. FARIDE RAMIREZ ', TRUE),
(3, 'COORDINACION_DE_EDUCACION_Y_JUSTICIA_MUNICIPAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_educacion_y_justicia_municipal', 'Coordinacion de Educacion y Justicia Municipal', TRUE),
(3, 'DIRECCION_DE_TALENTO_HUMANO@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'direccion_de_talento_humano', 'LCDA. GLENYS DELGADO', TRUE),
(3, 'DIVISION_DE_GESTION_DE_TALENTO_HUMANO@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_gestion_de_talento_humano', 'DIVISION DE GESTION DE TALENTO HUMANO', TRUE),
(3, 'COORDINACION_DE_CAPTACION_Y_CAPACITACION_DEL_PERSONAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_captacion_y_capacitacion_del_personal', 'Coordinacion de Captacion y Capacitacion del Personal', TRUE),
(3, 'COORDINACION_DE_BIENESTAR_SOCIAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_bienestar_social', 'Coordinacion de Bienestar Social', TRUE),
(3, 'DIVISION_DEL_AREA_LEGAL_Y_ARCHIVO@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_del_area_legal_y_archivo', 'ABG. THIANA JAIMES HERNANDEZ', TRUE),
(3, 'DIVISION_DE_NOMINAS_Y_PRESTACIONES@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_nominas_y_prestaciones', 'LCDO. LEONARDO DUARTE', TRUE),
(3, 'COORDINACION_DE_NOMINA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_nomina', 'Coordinacion de Nomina', TRUE),
(3, 'COORDINACION_DE_PRESTACIONES_SOCIALES@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_prestaciones_sociales', 'Coordinacion de Prestaciones Sociales', TRUE),
(3, 'CONTRATACION_COLECTIVA_OBREROS@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'contratacion_colectiva_obreros', 'CONTRATACION COLECTIVA OBREROS', TRUE),
(3, 'CONTRATACION_COLECTIVA_EMPLEADOS@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'contratacion_colectiva_empleados', 'CONTRATACION COLECTIVA EMPLEADOS', TRUE),
(3, 'DIRECCION_DE_PLANIFICACION_Y_PRESUPUESTO@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'direccion_de_planificacion_y_presupuesto', 'LCDA. DAYANA SANCHEZ', TRUE),
(3, 'DIVISION_DE_PLANIFICACION@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_planificacion', 'DIVISIÓN DE PLANIFICACIÓN', TRUE),
(3, 'DIVISION_DE_PRESUPUESTO@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_presupuesto', 'LCDA. DAYANA SANCHEZ', TRUE),
(3, 'DIRECCION_DE_ADMINISTRACION@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'direccion_de_administracion', 'LCDA. GLENYS DELGADO', TRUE),
(3, 'DIVISION_DE_COMPRAS@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_compras', 'LCDO PEDRO ZAMBRANO', TRUE),
(3, 'COORDINACION_DE_DEPOSITO@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_deposito', 'Coordinacion de Deposito', TRUE),
(3, 'DIVISION_DE_CONTABILIDAD@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_contabilidad', 'LCDA. NUBIA CASTRO ', TRUE),
(3, 'DIVISION_DE_BIENES@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_bienes', 'LCDO.  YORMAN E SOSA FERREIRA', TRUE),
(3, 'DIVISION_DE_SERVICIOS_GENERALES@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_servicios_generales', 'JUAN ALBERTO MARTINEZ', TRUE),
(3, 'DIVISION_DE_MANTENIMIENTO_VEHICULAR@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_mantenimiento_vehicular', 'DIVISION DE MANTENIMIENTO VEHICULAR', TRUE),
(3, 'SUPERINTENDENCIA_MUNICIPAL_DE_ADMINISTRACION_TRIBUTARIA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'superintendencia_municipal_de_administracion_tributaria', 'ABOG. ANTONIO MARTINEZ', TRUE),
(3, 'COORDINACION_DE_FISCALES@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_fiscales', 'MSc. YENYT VALERO', TRUE),
(3, 'COORDINACION_DE_ASUNTOS_LEGALES@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_asuntos_legales', 'ABG. DANIELA MALDONADO', TRUE),
(3, 'DIVISION_DE_ACTIVIDADES_ECONOMICAS@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_actividades_economicas', 'LCDA. MAYRA CARDENAS', TRUE),
(3, 'DIVISION_DE_RENTAS_MUNICIPALES@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_rentas_municipales', 'T.S.U.  FRANK LEONARDO ALVIAREZ', TRUE),
(3, 'OFICINA_DE_PUBLICIDAD_Y_PROPAGANDA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'oficina_de_publicidad_y_propaganda', 'OFICINA DE PUBLICIDAD Y PROPAGANDA', TRUE),
(3, 'OFICINA_DE_CONTROL_DE_LICORES_Y_ESPECTACULOS_PUBLICOS@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'oficina_de_control_de_licores_y_espectaculos_publicos', 'OFICINA DE CONTROL DE LICORES Y ESPECTÁCULOS PUBLICOS', TRUE),
(3, 'DIVISION_DE_COBRANZAS@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_cobranzas', 'DIVISION DE COBRANZAS', TRUE),
(3, 'DIVISION_DE_ATENCION_AL_CONTRIBUYENTE@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_atencion_al_contribuyente', 'TSU. NINETT MALDONADO', TRUE),
(3, 'CONCEJO_MUNICIPAL_BOLIVARIANO_DEL_MUNICIPIO_SAN_CRISTOBAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'concejo_municipal_bolivariano_del_municipio_san_cristobal', 'MARTA ORTIZ ', TRUE),
(3, 'CONTRALORIA_DEL_MUNICIPIO_SAN_CRISTOBAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'contraloria_del_municipio_san_cristobal', 'CONTRALORÍA DEL MUNICIPIO SAN CRISTOBAL', TRUE),
(3, 'INSTITUTO_AUTONOMO_DE_POLICIA_DEL_MUNICIPIO_SAN_CRISTOBAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'instituto_autonomo_de_policia_del_municipio_san_cristobal', 'INSTITUTO AUTÓNOMO DE POLICÍA DEL MUNICIPIO SAN CRISTÓBAL', TRUE),
(3, 'SECRETARIA_DE_SEGURIDAD_CIUDADANA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'secretaria_de_seguridad_ciudadana', 'DRA. GLEDY DELGADO', TRUE),
(3, 'COORDINACION_DE_SALA_SITUACIONAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_sala_situacional', 'Coordinacion de Sala Situacional', TRUE),
(3, 'CUERPO_DE_BOMBEROS@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'cuerpo_de_bomberos', 'CMDT. ANTONIO BRICEÑO ', TRUE),
(3, 'PROTECCION_CIVIL_MUNICIPAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'proteccion_civil_municipal', 'CNEL. RAFAEL CHACON', TRUE),
(3, 'COORDINACION_DE_GESTION_DE_RIESGOS@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_gestion_de_riesgos', 'Coordinacion de Gestion de Riesgos', TRUE),
(3, 'COORDINACION_DE_OPERACIONES@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_operaciones', 'Coordinacion de Operaciones', TRUE),
(3, 'COORDINACION_DE_EDUCACION@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_educacion', 'Coordinacion de Educacion', TRUE),
(3, 'DIRECCION_DE_PROMOCCION_Y_FOMENTO_DE_LA_PRODUCCION_AGROALIMENTARIA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'direccion_de_promoccion_y_fomento_de_la_produccion_agroalimentaria', 'DIRECCION DE PROMOCCION Y FOMENTO DE LA PRODUCCION AGROALIMENTARIA', TRUE),
(3, 'DIRECCION_DE_DEPORTE_Y_RECREACCION@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'direccion_de_deporte_y_recreaccion', 'PROF. JUANA B. SUAREZ U.', TRUE),
(3, 'COORDINACION_DE_ACTIVIDAD_FISICA_RECREACION_Y_MASIFICACION_MUNICIPAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_actividad_fisica_recreacion_y_masificacion_municipal', 'Coordinacion de Actividad Fisica, Recreacion y Masificacion Municipal', TRUE),
(3, 'DIRECCION_DE_VIALIDAD_TRANSITO_TRANSPORTE_E_INFRAESTRUCTURA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'direccion_de_vialidad_transito_transporte_e_infraestructura', 'ING. CARLOS ACOSTA', TRUE),
(3, 'DIVISION_DE_TRANSITO_Y_TRANSPORTE@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_transito_y_transporte', 'ING. ALBERT CONTRERAS', TRUE),
(3, 'COORDINACION_DE_OPERACIONES_DE_TRANSITO@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_operaciones_de_transito', 'Coordinacion de Operaciones de Transito', TRUE),
(3, 'COORDINACION_DE_ORDENAMIENTO_DE_TRANSPORTE@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_ordenamiento_de_transporte', 'Coordinacion de Ordenamiento de Transporte', TRUE),
(3, 'DIVISION_DE_VIALIDAD@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_vialidad', 'ING. DANIEL NAVARRO DUQUE', TRUE),
(3, 'COORDINACION_DE_ALUMBRADO_PUBLICO@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_alumbrado_publico', 'ING. VALDEMAR VASQUEZ', TRUE),
(3, 'COORDINACION_DE_SEMAFOROS@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_semaforos', 'Coordinacion de Semaforos', TRUE),
(3, 'COORDINACION_DE_DEMARCACION_Y_SENALAMIENTO_VIAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_demarcacion_y_senalamiento_vial', 'Coordinacion de Demarcacion y Señalamiento Vial', TRUE),
(3, 'DIVISION_DE_MANTENIMIENTO_VIAL_E_INFRAESTRUCTURA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_mantenimiento_vial_e_infraestructura', 'ING. DANIEL  NAVARRO DUQUE', TRUE),
(3, 'COORDINACION_DE_REDES_HIDRAULICAS_REJILLAS_Y_ALCANTARILLADO@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_redes_hidraulicas_rejillas_y_alcantarillado', 'Coordinacion de Redes Hidraulicas, Rejillas y Alcantarillado', TRUE),
(3, 'COORDINACION_DE_MOVIMIENTOS_DE_TIERRA_Y_CANALIZACIONES@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_movimientos_de_tierra_y_canalizaciones', 'Coordinación de Movimientos de Tierra y Canalizaciones', TRUE),
(3, 'COORDINACION_DE_MANTENIMIENTO_VIAL_Y_ROTURA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_mantenimiento_vial_y_rotura', 'Coordinación de Mantenimiento Vial y Rotura', TRUE),
(3, 'DIRECCION_DE_EDUCACION_MUNICIPAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'direccion_de_educacion_municipal', 'LCDA. ELAYNE EDITH MENDEZ', TRUE),
(3, 'DIVISION_DE_DOCENCIA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_docencia', 'DIVISION DE DOCENCIA', TRUE),
(3, 'DIVISION_DE_BIENESTAR_EDUCATIVO@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_bienestar_educativo', 'DIVISION DE BIENESTAR EDUCATIVO', TRUE),
(3, 'CONTRATACION_COLECTIVA_MAESTROS@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'contratacion_colectiva_maestros', 'CONTRATACION COLECTIVA MAESTROS', TRUE),
(3, 'DIRECCION_DE_CULTURA_MUNICIPAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'direccion_de_cultura_municipal', 'LCDO. ALEXANDER GARCIA', TRUE),
(3, 'COORDINACION_DE_ARTES_PLASTICAS_ESCENICAS_MUSICALES_Y_LITERATURA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_artes_plasticas_escenicas_musicales_y_literatura', 'Coordinación de Artes Plásticas, Escénicas, Musicales y Literatura.', TRUE),
(3, 'BANDA_MUNICIPAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'banda_municipal', 'PROF. ROSENDO ANTONIO ESPINOZA', TRUE),
(3, 'MEDIOS_COMUNICACIONALES_Y_MARKETING_DIGITAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'medios_comunicacionales_y_marketing_digital', 'LCDA.  LUISANA ARELLANO', TRUE),
(3, 'COORDINACION_DE_INFORMACION@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_informacion', 'Coordinacion de Información', TRUE),
(3, 'COORDINACION_DE_REDES_SOCIALES_Y_MEDIOS_DIGITALES@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_redes_sociales_y_medios_digitales', 'Coordinacion de Redes Sociales y Medios Digitales', TRUE),
(3, 'DIRECCION_DE_DESARROLLO_URBANO_LOCAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'direccion_de_desarrollo_urbano_local', 'LCDA. DALIA TERAN', TRUE),
(3, 'COORDINACION_DE_FISCALES_DE_CONTROL_URBANO@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_fiscales_de_control_urbano', 'Coordinacion de Fiscales de Control Urbano', TRUE),
(3, 'DIVISION_DE_INGENIERIA_MUNICIPAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_ingenieria_municipal', 'ING. CARMEN OSORIO', TRUE),
(3, 'DIVISION_DE_PLANIFICACION_URBANA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_planificacion_urbana', 'LCDA.  DALIA TERAN', TRUE),
(3, 'DIVISION_DE_CATASTRO@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_catastro', 'DIVISION DE CATASTRO', TRUE),
(3, 'OFICINA_TECNICA_DE_CATASTRO@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'oficina_tecnica_de_catastro', 'Oficina tecnica de catastro', TRUE),
(3, 'OFICINA_LEGAL_DE_CATASTRO@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'oficina_legal_de_catastro', 'Oficina legal de catastro', TRUE),
(3, 'COORDINACION_DE_TIERRAS@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_tierras', 'LCDA. (MSc) AINARU SANCHEZ MUÑOZ', TRUE),
(3, 'DIVISION_DE_PROTECCION_AMBIENTAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_proteccion_ambiental', 'LCDO. GERSON H. MONSALVE U.', TRUE),
(3, 'PROYECTOS_MUNICIPALES@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'proyectos_municipales', 'PROYECTOS MUNICIPALES', TRUE),
(3, 'DIRECCION_DE_CONSTRUCCION_DE_OBRAS_MUNICIPALES@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'direccion_de_construccion_de_obras_municipales', 'DIRECCION DE CONSTRUCCION DE OBRAS MUNICIPALES', TRUE),
(3, 'DIVISION_DE_CONSTRUCCION_Y_REHABILITACION_DE_ESPACIOS_PUBICOS@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_construccion_y_rehabilitacion_de_espacios_pubicos', 'DIVISIÓN DE CONSTRUCCION Y REHABILITACION DE ESPACIOS PUBICOS', TRUE),
(3, 'COORDINACION_DE_DESMALEZAMINETO_DE_CALLES_AVENIDAS_Y_ESPACIOS_PUBLICOS@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_desmalezamineto_de_calles_avenidas_y_espacios_publicos', 'Coordinacion de Desmalezamineto de Calles, Avenidas y Espacios Publicos', TRUE),
(3, 'COORDINACION_DE_EMBELLECIMIENTO_DE_FACHADAS_Y_ELABORACION_DE_MURALES@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_embellecimiento_de_fachadas_y_elaboracion_de_murales', 'Coordinacion de Embellecimiento de Fachadas y Elaboracion de Murales', TRUE),
(3, 'COORDINACION_DE_OBRAS@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_obras', 'Coordinacion de Obras', TRUE),
(3, 'DIRECCION_DE_SERVICIOS_PUBLICOS@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'direccion_de_servicios_publicos', 'LCDA. DALIA ROSA TERAN GONZALEZ', TRUE),
(3, 'DIVISION_DE_SERVICIOS_MUNICIPALES@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_servicios_municipales', 'DIVISIÓN DE SERVICIOS MUNICIPALES', TRUE),
(3, 'COORDINACION_DE_ASEO_URBANO@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_aseo_urbano', 'ING. LUIS ANTONIO UZCATEGUI ', TRUE),
(3, 'COORDINACION_DEL_MERCADO_MUNICIPAL_LA_GUAYANA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_del_mercado_municipal_la_guayana', 'Coordinacion del Mercado Municipal La Guayana', TRUE),
(3, 'COORDINACION_DEL_MERCADO_MUNICIPAL_LA_VILLA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_del_mercado_municipal_la_villa', 'Coordinacion del Mercado Municipal La Villa', TRUE),
(3, 'COORDINACION_DEL_MERCADO_MUNICIPAL_DE_SANTA_TERESA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_del_mercado_municipal_de_santa_teresa', 'Coordinacion del Mercado Municipal de Santa Teresa', TRUE),
(3, 'COORDINACION_DEL_MERCADO_MUNICIPAL_LA_ERMITA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_del_mercado_municipal_la_ermita', 'LCDO. DARIO MARTINEZ', TRUE),
(3, 'COORDINACION_DEL_CEMENTERIO_MUNICIPAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_del_cementerio_municipal', 'TEC. HECTOR ALONSO BECERRA', TRUE),
(3, 'DIRECCION_DE_AMBIENTE_Y_DESARROLLO_SOSTENIBLE@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'direccion_de_ambiente_y_desarrollo_sostenible', 'DIRECCION DE AMBIENTE Y DESARROLLO SOSTENIBLE', TRUE),
(3, 'COORDINACION_DE_AMBIENTE@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_ambiente', 'Coordinacion de Ambiente', TRUE),
(3, 'COORDINACION_DE_DESARROLLO_SOSTENIBLE@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_desarrollo_sostenible', 'Coordinacion de Desarrollo Sostenible', TRUE),
(3, 'COORDINACION_DEL_VIVERO_MUNICIPAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_del_vivero_municipal', 'ING. CARMEN CORREDOR', TRUE),
(3, 'DIRECCION_DE_VIVIENDA_MUNICIPAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'direccion_de_vivienda_municipal', 'ING. KARELIS MORA', TRUE),
(3, 'COORDINACION_DE_EVALUACION_Y_ATENCION_SOCIAL_DE_VIVIENDA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_evaluacion_y_atencion_social_de_vivienda', 'Coordinación de Evaluación y Atención Social de Vivienda', TRUE),
(3, 'DIVISION_DE_DESARROLLO_Y_CONSERVACION_DE_VIVIENDA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_desarrollo_y_conservacion_de_vivienda', 'DIVISION DE DESARROLLO Y CONSERVACION DE VIVIENDA', TRUE),
(3, 'SERVICIO_AUTONOMO_TERMINAL_DE_PASAJERO_ING_TEOFILO_CARDENAS@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'servicio_autonomo_terminal_de_pasajero_ing_teofilo_cardenas', 'SERVICIO AUTONOMO TERMINAL DE PASAJERO ING TEOFILO CARDENAS', TRUE),
(3, 'DIRECCION_DE_SALUD_MUNICIPAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'direccion_de_salud_municipal', 'ING. CARLOS ACOSTA', TRUE),
(3, 'COORDINACION_DE_LOS_CENTROS_DE_SALUD_COMUNITARIOS@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'coordinacion_de_los_centros_de_salud_comunitarios', 'Coordinacion de los centros de salud comunitarios', TRUE),
(3, 'DIVISION_DE_ATENCION_PRIMARIA_EN_SALUD@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'division_de_atencion_primaria_en_salud', 'DIVISION DE ATENCION PRIMARIA EN SALUD', TRUE),
(3, 'INSTITUTO_AUTONOMO_MUNICIPAL_DE_DESARROLLO_INTEGRAL_DE_SAN_CRISTOBAL@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'instituto_autonomo_municipal_de_desarrollo_integral_de_san_cristobal', 'ING. JANICE GONZALEZ', TRUE),
(3, 'SISTEMA_DE_PROTECCION_INTEGRAL_DEL_NINO_NINA_Y_DEL_ADOLESCENTE@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'sistema_de_proteccion_integral_del_nino_nina_y_del_adolescente', 'ABG. VIVIANA CASTILLO', TRUE),
(3, 'CONSEJO_DE_PROTECCION@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'consejo_de_proteccion', 'CONSEJO DE PROTECCIÓN', TRUE),
(3, 'CONSEJO_MUNICIPAL_DE_DERECHO@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'consejo_municipal_de_derecho', 'CONSEJO MUNICIPAL DE DERECHO', TRUE),
(3, 'DEFENSORIA_DEL_NINO_NINA_Y_ADOLECENTE@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'defensoria_del_nino_nina_y_adolecente', 'DEFENSORIA DEL NIÑO, NIÑA Y ADOLECENTE', TRUE),
(3, 'ESCUELA_JOSE_GONZALO_MENDEZ@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'escuela_jose_gonzalo_mendez', 'LCDA. BELKIS VASQUEZ', TRUE),
(3, 'ESCUELA_JUANA_MALDONADO_G@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'escuela_juana_maldonado_g', 'MSC KAROL BUSTAMANTE', TRUE),
(3, 'ESCUELA_LUISA_CACERES_DE_ARISMENDI@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'escuela_luisa_caceres_de_arismendi', 'LCDA. ISABEL MEDINA', TRUE),
(3, 'ESCUELA_REGINA_DE_VELAZQUEZ@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'escuela_regina_de_velazquez', 'LCDA. ELAYNE E. MENDEZ ', TRUE),
(3, 'ESCUELA_SAN_JOSE@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'escuela_san_jose', 'PROF. MARIELA VEGA', TRUE),
(3, 'ESCUELA_MARCO_TULIO_RAMIREZ_ROA@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'escuela_marco_tulio_ramirez_roa', 'LCDA. MSC. MARIBEL SANCHEZ', TRUE),
(3, 'ESCUELA_SIMON_RODRIGUEZ@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'escuela_simon_rodriguez', 'MSc. MARIBELCY PEREZ', TRUE),
(3, 'ESCUELA_ROMULO_GALLEGOS@tickets.gob', '$2y$12$kuWuI.ZL1CzTIrhOZwEtiOo9Z51ufqTu8QIP1xe2WNzoI40yDOmGe', 'escuela_romulo_gallegos', 'LCDA. LINDA PARADA', TRUE);
