INSERT INTO `Software_Systems` (`ID_System`, `System_Name`, `Description`, `Status`) VALUES
(1, 'SISSA', 'Agregado desde formulario de actas', 'activo'),
(2, 'SIRAD', 'Agregado desde formulario de actas', 'activo'),
(3, 'CONSUMIBLES', 'Agregado desde formulario de actas', 'activo'),
(4, 'SIRED', 'Agregado desde formulario de actas', 'activo'),
(5, 'SIRA', 'Agregado desde formulario de actas', 'activo'),
(6, 'GAITAS', 'Agregado desde formulario de actas', 'activo'),
(7, 'RECICLAJE', 'Agregado desde formulario de actas', 'activo'),
(8, 'POESIA', 'Agregado desde formulario de actas', 'activo'),
(9, 'SISCO', 'Agregado desde formulario de actas', 'activo'),
(10, 'SIRAD-ACTAS', 'Agregado desde formulario de actas', 'activo'),
(11, 'ECONOMIA INFORMAL', 'Agregado desde formulario de actas', 'activo'),
(12, 'VOLUNTARIADO', 'Agregado desde formulario de actas', 'activo'),
(13, 'FACTURAS', 'Agregado desde formulario de actas', 'activo'),
(14, 'CONSTANCIA DE PAGO', 'Agregado desde formulario de actas', 'activo'),
(15, 'CERTIFICADOS', 'Agregado desde formulario de actas', 'activo'),
(16, 'JORNADA MEDICA', 'Agregado desde formulario de actas', 'activo'),
(17, 'TURNERO', 'Agregado desde formulario de actas', 'activo'),
(18, 'TAQUILLA UNICA', 'Agregado desde formulario de actas', 'activo'),
(19, 'SISMUN', 'Agregado desde formulario de actas', 'activo'),
(20, 'SIGESP', 'Agregado desde formulario de actas', 'activo'),
(21, 'SISTEMA DE PERMISOS DE CONSTRUCCION', 'Agregado desde formulario de actas', 'activo'),
(22, 'reto', 'Agregado desde formulario de actas', 'activo'),
(23, 'SGEXPEDIENTES', 'Agregado desde formulario de actas', 'activo'),
(25, 'reingeniería', 'Agregado desde formulario de actas', 'activo'),
(26, 'tickera', 'Agregado desde formulario de actas', 'activo'),
(27, 'SISTEMA CONSULTA DE NOMINAS EN VFPRO', 'Agregado desde formulario de actas', 'activo'),
(28, 'SISTEMA DE PAGOS 2022', 'Agregado desde formulario de actas', 'activo'),
(29, 'SISTEMA NOMINAS Y FAOV', 'Agregado desde formulario de actas', 'activo'),
(30, 'SIREC', 'Agregado desde formulario de actas', 'activo'),
(31, 'VPS Pagina web', 'Agregado desde formulario de actas', 'activo'),
(32, 'ingenieria', 'Agregado desde formulario de actas', 'activo'),
(33, 'API BIENES', 'Agregado desde formulario de actas', 'activo'),
(34, 'consulta de bienes', 'Agregado desde formulario de actas', 'activo');
